<a href="https://colab.research.google.com/github/mayankcircle/Tensorflow-2.0/blob/main/Tensorflow_Tutorial_2_(Tensor_Basics).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [ ]:
tf.__version__

'2.3.0'

# Tensor Initialization

Tensor Initialization - Scalar (INT)

In [ ]:
x = tf.constant(4)
x

<tf.Tensor: shape=(), dtype=int32, numpy=4>

Tensor Initialization - Scalar (FLOAT)

In [ ]:
x = tf.constant(4.0)
x

<tf.Tensor: shape=(), dtype=float32, numpy=4.0>

**Tensor Initialization - Scalar (Recommended Way)**

In [ ]:
x = tf.constant(4,shape=(1,1),dtype=tf.float32)
x

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[4.]], dtype=float32)>

**Tensor Initialization - 2 x 3 Matrix (Recommended Way)**

In [ ]:
x = tf.constant([[1,2,3],[4,5,6]])
x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

Tensor Initialization - convert 2 x 3 matrix (list) to 3 x 2 matrix using shape argument 

In [ ]:
x = tf.constant([[1,2,3],[4,5,6]],shape=(3,2))
x

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

**Tensor Initialization - Square Unit Matrix**

In [ ]:
x = tf.ones((3,3)) # shape
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

**Tensor Initialization - Square Zero Matrix**

In [ ]:
x = tf.zeros((3,3))
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

**Tensor Initialization - Identity Matrix**

In [ ]:
x = tf.eye(3) # num of rows
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

**Tensor Initialization - 2 x 3 Matrix initialized from normal distribution randomly**

In [ ]:
x = tf.random.normal((2,3),mean=0,stddev=1)
x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 0.10302696,  0.05144438,  1.5829542 ],
       [-0.05029459,  0.29154932,  1.3752288 ]], dtype=float32)>

**Tensor Initialization - 2 x 3 Matrix initialized from uniform distribution randomly**

In [ ]:
x = tf.random.uniform((2,3),minval=10, maxval=20) # all random values are distributed uniformly between min and max val
x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[11.095119, 19.778282, 11.967712],
       [12.549023, 10.889803, 15.092335]], dtype=float32)>

**Tensor Initialization - using range**

In [ ]:
tf.range(start=1,limit=10,delta=2) # delta is step
# shortcut : tf.range(1,10,2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9], dtype=int32)>

**Convert dtype of a tensor using cast**

In [ ]:
tf.cast(x, dtype=tf.float64) # out-of-place ops

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[ 0.10302696,  0.05144438,  1.58295417],
       [-0.05029459,  0.29154932,  1.37522876]])>

# Mathmatical Operations

In [6]:
x = tf.constant([1,2,3])
y = tf.constant([4,5,6])

**Elementwise Addition of Two Tensors**

In [ ]:
z = tf.add(x,y)
# shortcut (Recommended Way) : z = x + y 
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 7, 9], dtype=int32)>

**Elementwise Subtraction of Two Tensors**

In [ ]:
z = tf.subtract(x,y)
# shortcut (Recommended Way) : z = x - y 
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-3, -3, -3], dtype=int32)>

**Elementwise Division of Two Tensors**

In [ ]:
z = tf.divide(x,y)
# shortcut : z = x / y
z

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.25, 0.4 , 0.5 ])>

**Elementwise Multiplication of Two Tensors**

In [ ]:
z = tf.multiply(x,y)
# shortcut : z = x * y
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 4, 10, 18], dtype=int32)>

**Dot Product of Two Tensors**

In [7]:
# dot product is simple elementwise multiplication followed by summation along cols
z = tf.tensordot(x,y,axes=1)
z

<tf.Tensor: shape=(), dtype=int32, numpy=32>

In [13]:
# same result can be acheived using reduce_sum() function
z = tf.reduce_sum(x*y,axis=0)
z

<tf.Tensor: shape=(), dtype=int32, numpy=32>

**Matrix Multiplication of two Tensors**

In [16]:
x = tf.random.normal((2,3))
y = tf.random.normal((3,4))

In [17]:
z = tf.matmul(x, y) # x and y matrix dim should be conformative
z

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[-2.4731774 ,  1.6940482 , -3.3398454 ,  0.52422094],
       [-1.5278528 , -1.0074003 , -2.8584425 ,  1.231631  ]],
      dtype=float32)>

In [19]:
# or we can do this way (Recommended way)
z = x @ y
z

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[-2.4731774 ,  1.6940482 , -3.3398454 ,  0.52422094],
       [-1.5278528 , -1.0074003 , -2.8584425 ,  1.231631  ]],
      dtype=float32)>

**Element-wise Exponentiation in a Tensor**

In [14]:
z = x ** 5
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([  1,  32, 243], dtype=int32)>

# Indexing

In [22]:
x = tf.constant([0,1,2,1,2,3,3,3,1,5])
x[:]

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 1, 2, 3, 3, 3, 1, 5], dtype=int32)>

In [23]:
x[1:]

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 1, 2, 3, 3, 3, 1, 5], dtype=int32)>

In [25]:
x[-3:-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 1], dtype=int32)>

In [26]:
x[0:8:3]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([0, 1, 3], dtype=int32)>

In [31]:
x[::-1]

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([5, 1, 3, 3, 3, 2, 1, 2, 1, 0], dtype=int32)>

Indexing in 2 D Tensor

In [34]:
y = tf.constant([[1,2,3],[4,5,6]])
y

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [35]:
# getting 1st row
y[0]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [37]:
# or : getting 1st row
y[0,:]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [38]:
# getting 1st and 2nd column of 1st row
y[0,0:2]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

**Gather Data of Specific indices in Tensor**

In [33]:
# x[[0,3,4]] it will give error
indices = tf.constant([0,3,4])

tf.gather(x,indices)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([0, 1, 2], dtype=int32)>

# Reshaping a Tensor

In [45]:
x = tf.range(9)
x

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)>

In [46]:
z = tf.reshape(x,(3,3))
z

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int32)>

**Transpose a tensor**

In [47]:
zz = tf.transpose(z)
zz

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]], dtype=int32)>