<a href="https://colab.research.google.com/github/mayankcircle/Tensorflow-2.0/blob/main/Tensorflow_Tutorial_2_(Tensor_Basics).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.3.0'

Tensor Initialization - Scalar (INT)

In [3]:
x = tf.constant(4)
x

<tf.Tensor: shape=(), dtype=int32, numpy=4>

Tensor Initialization - Scalar (FLOAT)

In [4]:
x = tf.constant(4.0)
x

<tf.Tensor: shape=(), dtype=float32, numpy=4.0>

**Tensor Initialization - Scalar (Recommended Way)**

In [5]:
x = tf.constant(4,shape=(1,1),dtype=tf.float32)
x

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[4.]], dtype=float32)>

**Tensor Initialization - 2 x 3 Matrix (Recommended Way)**

In [6]:
x = tf.constant([[1,2,3],[4,5,6]])
x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

Tensor Initialization - convert 2 x 3 matrix (list) to 3 x 2 matrix using shape argument 

In [7]:
x = tf.constant([[1,2,3],[4,5,6]],shape=(3,2))
x

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

**Tensor Initialization - Square Unit Matrix**

In [8]:
x = tf.ones((3,3)) # shape
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

**Tensor Initialization - Square Zero Matrix**

In [11]:
x = tf.zeros((3,3))
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

**Tensor Initialization - Identity Matrix**

In [13]:
x = tf.eye(3) # num of rows
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>